# Generated by Django 5.0.2 on 2024-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
