# Generated by Django 5.1.1 on 2024-09-14 16:42

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_current_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('audio', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_streak',
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
